import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ToggleButton from "./components/ToggleButton/ToggleButton";
import Sidebar from "./components/Sidebar/Sidebar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Projeto - Sistema Simplificado de Gestão de OKRs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Sidebar />
        <ToggleButton />
      </body>
    </html>
  );
}
